### ISSUE TITLE
Unable to select more than 5 stars with default size settings

### ISSUE THREAD

**Issue by paoloq** [evgenyneu/Cosmos#60] opened 2017-05-26 16:22 UTC
I set 6 total stars and a star size of 30.0, in this way I cannot select more than 4 stars.
Setting 6 total star and the default star size, I cannot select more than 5 stars.
Seems like the touchable area remains always at the default size, not updating once the drawn area changed.

**Comment by evgenyneu** [comment] 2017-05-26 22:18
Hi @paoloq, thanks for reporting this problem. I created a CosmosView with six stars of size 30 and could not reproduce your problem unfortunately. I was able to select all six stars, see the attached demo. Am I missing something? There is probably something else that affects the view.

Xcode 8.3.2,  iOS 10.3 simulator, macOS 10.12.4.

[SixStarsDemo.zip](https://github.com/marketplacer/Cosmos/files/1033057/SixStarsDemo.zip)

**Comment by paoloq** [comment] 2017-05-26 22:54
Sorry, I forgot to say that I didn't use Storyboard but code only. Would you mind to try without Storyboard? Thank you

**Comment by evgenyneu** [comment] 2017-05-26 23:14
It's alright, here is the updated demo that creates a cosmos view from code :)

[SixStarsDemo_fromCode.zip](https://github.com/marketplacer/Cosmos/files/1033132/SixStarsDemo_fromCode.zip)

**Comment by paoloq** [comment] 2017-05-26 23:57
Ok it works using NSLayoutConstraint. It's not working without using it. If I use your code commenting positionCosmos() function and simply add a cosmos.frame.origin.y = 100.0, I can't press the last two stars.

**Comment by evgenyneu** [comment] 2017-05-27 00:39
Thanks for clarification. Sorry, I assumed you were using autolayout. :)

Without autolayout, one needs to update the size of the view manually, so the width and height of the view expands to fit the size of the stars inside:

```
cosmos.frame.size = cosmos.intrinsicContentSize
```

You can check if the size of the view is correct by showing the border:
```
cosmos.layer.borderWidth = 1
cosmos.layer.borderColor = UIColor.red.cgColor
```

Here is the updated demo:

[SixStarsDemo_noAutoLayout.zip](https://github.com/marketplacer/Cosmos/files/1033194/SixStarsDemo_noAutoLayout.zip)

Let me know how it goes :)

**Comment by paoloq** [comment] 2017-05-27 09:41
Wonderful, `cosmos.frame.size = cosmos.intrinsicContentSize` is the key. 
Thanks a lot for your help, you walked me through this issue and you solved it.

A final thought, would it be a problem to support a "code only without AutoLayout" approach, adding 
`self.frame.size = viewSize` on `private func updateSize(_ layers: [CALayer])` after `viewSize` is updated?

Would it affect other parts of the code, would it increase some redundancy?

I'd love to have that kind of support directly on your code, but if it's a problem I'll workaround.

Thanks again!

**Comment by evgenyneu** [comment] 2017-05-27 10:49
Thanks, I am glad that it helped. :)
Your suggestion is very good. I am looking how UILabel implements it. They require one to call `siteToFit()` to stretch the view to the size of the text, it it is used without Auto Layout. According to documentation we can override `sizeThatFits` method and return the size for the CosmosView, which is updated each time you set its property, like the margin size:

```Swift
override open func sizeThatFits(_ size: CGSize) -> CGSize {
    return viewSize;
}
```

Then, one will need to call `cosmos.siteToFit()` (instead of `cosmos.frame.size = cosmos.intrinsicContentSize`) to update the bounds of the view. Does it sound like a good idea to you? :)

**Comment by evgenyneu** [comment] 2017-06-07 02:32
@paoloq, I decided to go with your solution. The CosmosView will resize automatically when its settings are updated. Released as version `10`. Thanks a lot for your help. :)

**Comment by paoloq** [comment] 2017-06-07 08:03
I'm sorry I didn't reply before, but I was super busy.
I'm glad you decided to include my solution. I didn't update to version 10 yet, but I will asap!
I'll let you know if I see any issue related to the new code.
Best ✌️

**Comment by evgenyneu** [comment] 2017-06-08 00:17
@paoloq thanks, let me know how it goes.

**Comment by evgenyneu** [comment] 2017-07-14 04:43
Closing the issue. Feel free to reopen if needed.

**Closed by evgenyneu** 2017-07-14 04:43 UTC
