### ISSUE TITLE
CosmosView not updating to touch events in ScrollView

### ISSUE THREAD

**Issue by SlavcoPetkovski** [evgenyneu/Cosmos#37] opened 2016-08-09 09:24 UTC
I have a ScrollView -> View -> CosmosView. All `UserInteractionEnabled` properties are ON. I can change the rating on the stars by swiping easily, but tapping on them is very hard. Maybe is because the tap events are not well handled here, i don't know, but all config of the scrollview and view are by default. Any help? [https://s10.postimg.org/nkklw7rrd/Screen_Shot_2016_08_09_at_11_24_29_AM.png](url)

**Comment by evgenyneu** [comment] 2016-08-12 23:31
Hello @SlavcoPetkovski, thank you for the feedback, this is very interesting. I created a demo app with a scrollview. Cosmos view seems to change stars for me without any problem, whether I tap it or swipe. I tried it both in the Simulator and on device and could not reproduce this problem 

![cosmos_in_scroll_view](https://cloud.githubusercontent.com/assets/880411/17639730/6bfde3c2-6138-11e6-964e-5d216cf13b34.gif)

Here is the demo app project (Xcode 8 beta 4):

[UsingCosmosInScrollView.zip](https://github.com/marketplacer/Cosmos/files/416291/UsingCosmosInScrollView.zip)

Do you think you could isolate your issue in a demo app so I can try it?

**Comment by evgenyneu** [comment] 2016-09-09 07:31
Hi @SlavcoPetkovski, do you still have the issue?

**Comment by SlavcoPetkovski** [comment] 2016-09-09 08:19
I dont have xcode 8 ... Cant test the sample project

**Comment by evgenyneu** [comment] 2016-09-09 08:42
Oh sorry, here is the Xcode 7 demo.

[UsingCosmosInScrollViewXcode7.zip](https://github.com/marketplacer/Cosmos/files/463560/UsingCosmosInScrollViewXcode7.zip)

**Comment by SlavcoPetkovski** [comment] 2016-09-09 16:28
Weird, tried everything but in your projects everything is smooth, but in mine i present the view controller with self.storyboard.instantiate and it is hard to set rating. It works but you have to be very precise on the star...

**Comment by evgenyneu** [comment] 2016-09-09 21:58
This is very puzzling indeed. I would suggest isolating you case in a sample app, to reduce the complexity. It may help finding the cause of the issue. It probably involves the layout and positioning of the CosmosView, as well as the size of it, since it influences the touch target. I know it is very general advice bit it is hard to be more specific without looking at the code. Let me know how it goes.

**Comment by ankraft** [comment] 2017-01-16 23:52
I encountered the same or at least a very similar problem.

- I have Cosmos rating view in a cell defined in a storyboard for a UITableView
- I added a block to the rating for "didFinishTouchingCosmos"
- Select a star or swipe to left to remove a rating
- While keeping my finger (mouse in the simulator) touching the screen, I start to swipe up or down
- When stop the touch, the block assigned above doesn't fire, but the value of the rating still changes

I hope this help.

**Comment by evgenyneu** [comment] 2017-01-17 00:28
Hi @ankraft, thanks for reporting. Do you mind creating a new issue for this? It may be a different problem, since it occurs in the table view and not in the scroll view. Just want to keep things organized so we can address them one by one. Thanks

**Comment by ankraft** [comment] 2017-01-17 15:01
I forgot to mention: The superview of the table is a scroll view.
As long as there is no vertical scrolling the rating view works fine. I have the feeling that in case when another view starts to scroll the rating view looses the focus but the "didFinishTouchingCosmos" block isn't executed.

**Comment by evgenyneu** [comment] 2017-01-21 00:47
@ankraft, you are right. It looks like, once you start scrolling, the scroll view does not pass touches to its subviews and CosmosView does not receive them. I managed to make it work my disabling **Cancellable Content Touches** for the scroll view.

<img width="694" alt="cosmos_scroll_view_cancellable_content_touches" src="https://cloud.githubusercontent.com/assets/880411/22170206/4b0eec18-dfcf-11e6-95b7-be4b1c00ff5b.png">


Here is the demo app.

[UsingCosmosInScrollView.zip](https://github.com/marketplacer/Cosmos/files/720803/UsingCosmosInScrollView.zip)


Let me know if it works for you.

**Comment by ankraft** [comment] 2017-01-21 11:11
@evgenyneu, thanks a lot for looking into this. Your solution works perfectly with my app! 
Regarding the side effect: I think that it is actually a better UX not to scroll the view when the user is interacting with a control in that view.
Perhaps you should copy the screenshot and the explanation to the usage section in the README.md :)
Thanks again!

**Comment by evgenyneu** [comment] 2017-01-21 11:17
I am glad it helped. I will put it in the readme, as you suggested, since it can be a common problem. All the best.

**Comment by Rommanski** [comment] 2017-03-24 11:16
Hello @evgenyneu thank you for fantastic library.
I have cosmos view in table view (inside UITableViewCell). 'Cancellable Content Touches' is disabled. But 'didTouchCosmos' doesn't work sometime. I'm using swift_2.3 branch.
Can you advice me something?

**Comment by evgenyneu** [comment] 2017-03-24 11:31
Hi @Rommanski, thank you for kind words. For which view 'Cancellable Content Touches' is disabled? Could you describe how you interact with the table view when it does not fire `didTouchCosmos`? Thanks.

**Comment by Rommanski** [comment] 2017-03-24 11:38
Hello @evgenyneu. Thank you for your quick response.

I have disabled 'Cancellable Content Touches' for table view. But looks like I solved an issue. I'm using `didFinishTouchingCosmos` instead of `didTouchCosmos`.

> Could you describe how you interact with the table view when it does not fire didTouchCosmos?

Cell has rating view, and user just clicks. I do not feel any different in user behaviors when `didTouchCosmos` doesn't fire.

Thank you so much again!

**Comment by evgenyneu** [comment] 2017-03-24 22:46
@Rommanski I am glad you found a solution. It is still weird that `didTouchCosmos` did not work though.

**Comment by iverde** [comment] 2017-06-06 14:35
I had similar problems in a Scroll View with start's size of 30. In my case was because of CosmosView's size.
You can try this:
`cosmosView.backgroundColor = UIColor.blue`
If background does not cover all, that is the problem. You can modify size manually like this: 
`cosmosView.frame = GCRect(X: 100, y:100, width: 300, height: 300)`
Great library anyway, thanks @evgenyneu ;)

**Comment by evgenyneu** [comment] 2017-06-07 02:41
@iverde, thanks for reporting. It looks like your issue with the frame size was similar to the one that was fixed today in version 10. There should be no need to update the frame size manually from now on. :)

**Comment by evgenyneu** [comment] 2017-11-21 02:47
Closing the issue. Feel free to reopen if needed.

**Closed by evgenyneu** 2017-11-21 02:47 UTC

**Comment by s4cha** [comment] 2018-04-17 10:27
Hello ! First, thanks for this amazing tool !
I just had the same issue and thank god I found this thread.

Just wanted to add a little detail is that when devloping views in code, without storyboards, then 
scrollView.delaysContentTouches is `false` by default.
Thankfully I saw @evgenyneu screenshot I tried this setting :)

So the fix (in code) is:
```swift
scrollView.canCancelContentTouches = false
scrollView.delaysContentTouches = false
```

Cheers,

**Comment by evgenyneu** [comment] 2018-04-17 10:31
@s4cha, thanks for sharing your solution. 👍

**Comment by NiyogRay** [comment] 2018-07-28 15:57
Thankfully I found this issue thread :) I am wondering how the native UISlider manages to work fine in a UIScrollView. Could something similar be done by default for Cosmos, so we dont have to worry about disabling 'Can Cancel on Scroll' (that's what it's called in Xcode 9.4.1) ?

**Comment by NiyogRay** [comment] 2018-07-28 16:03
@s4cha thanks for your solution, but you accidentally wrote:

`scrollView.delaysContentTouches = false`

instead of what you meant

`scrollView.delaysContentTouches = true`
